/* 
The DOM is essential for various dynamic web developement task, including:

1. Modifying content: Developers can add, remove or modify elements and their attriburts
  enabling real-time updates to web pages

2. Event Handling: Interactions with users is made possible through event listeners
   attached to DOM elements. This allows for responsive and interactive web experience

3. Animating Elements: Animations can be achieved by manipulating css styles and
    properties of DOM elements

4. Fetching and Sending DATA

*/
